version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.33
    restart: always
    ports:
      - '4467:4467'
    environment:
      PRISMA_CONFIG: |
        port: 4467
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - '27016:27016'
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo: ~